### ISSUE TITLE
Create list of multiple items with commas, "and" before last list item

### ISSUE THREAD

**Issue by whoisgina** [oof-bar/craft-utils#1]
Basically this functionality: 

```
{% for author in entry.authors %}
   {{ author }}{{ loop.index < loop.length-1 ? ', ' : loop.index < loop.length ? ' & ' }}
{% endfor %}
```

Maybe the output could be a string that you can save in a variable and use many times in a template?

**Comment by AugustMiller** [comment]
Yep yep yep.

The two “joining” strings should represent "all" and "last", like this:

```twig
{% set titles = entry.authors | toList('title', ', ', ' & ') %}
<h2>{{ titles }}</h2>
```

Internally, we might also want to implement a `pluck` filter, to fetch properties as an array:

```twig
{% set titlesArray = entry.authors | pluck('title') %}
```

Anything more, I think a normal loop would do fine with—particularly if you need to wrap each element in a `li` or link each element.

**Comment by AugustMiller** [comment]
Implemented a `toList` filter in d8b472f731a7a026a1c49f597e2eb725cc299f82!

`pluck` is not implemented, though.

One neat side-effect: some EntryModel properties seem to still be usable, so you can do something like…

```twig
{{ entry.myRelationField | toList('link', ', ', ' & ') | raw }}
```

…to output a list of links for each of the categories, since `link` happens to generate an anchor tag. `raw` just makes sure the HTML comes through (otherwise, it's considered text and you get HTML entities).

**Comment by whoisgina** [comment]
Nice nice nice nice nice! 👌

**Comment by AugustMiller** [comment]
Just added [`pluck`](https://github.com/oof-bar/craft-utils/blob/master/readme.md#pluckprop) to the available Twig filters! Nice companion method for this.

Closing!
